services:

  central:
    image: inductiveautomation/ignition:8.3.9
    container_name: renasys-central
    ports:
      - "8088:8088"
    environment:
      ACCEPT_IGNITION_EULA: "Y"
    volumes:
      - central-data:/usr/local/bin/ignition/data
      - ../gateways/central/config:/usr/local/bin/ignition/data/config
      - ../gateways/central/projects:/usr/local/bin/ignition/data/projects

  edge-01:
    image: inductiveautomation/ignition:8.3.9
    container_name: renasys-edge-01
    ports:
      - "8188:8088"
    environment:
      ACCEPT_IGNITION_EULA: "Y"
    volumes:
      - edge-data:/usr/local/bin/ignition/data

volumes:
  central-data:
  edge-data: