services:

  central:
    image: inductiveautomation/ignition:8.3.9
    container_name: renasys-central
    ports:
      - "8088:8088"
    environment:
      ACCEPT_IGNITION_EULA: "Y"
    volumes:
      - central-data:/usr/local/bin/ignition/data
      - ../../config:/usr/local/bin/ignition/data/config
      - ../../projects:/usr/local/bin/ignition/data/projects


volumes:
  central-data: