services:

  edge-01:
    image: inductiveautomation/ignition:8.3.9
    container_name: renasys-edge-01
    ports:
      - "8188:8088"
    environment:
      ACCEPT_IGNITION_EULA: "Y"
    volumes:
      - edge-data:/usr/local/bin/ignition/data

volumes:
  edge-data: